### ISSUE TITLE
Final Checklist

### ISSUE THREAD

**Issue by austin-s970** [austin-s970/OOP-Connect4#24]
- [x] Finish Design Analysis (4+1 View)
- [x] Add Iterator Design Pattern
- [x] Add UML Diagrams representing the final code
- [x] Do more unit testing for Board(?)
- [x] Unit test Game
- [x] Add any necessary screenshots (if any)
- [x] Put the powerpoint (google slide) together
